DROP DATABASE IF EXISTS cryptodb;
CREATE DATABASE cryptodb;
\c cryptodb;

DROP TABLE IF EXISTS "user";

CREATE TABLE IF NOT EXISTS "user" (
  id BIGSERIAL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS "cryptocurrency";

CREATE TABLE IF NOT EXISTS "cryptocurrency" (
  id BIGSERIAL,
  name VARCHAR(255) NOT NULL,
  symbol VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS "transaction";

CREATE TABLE IF NOT EXISTS "transaction" (
  id BIGSERIAL,
  user_id INTEGER NOT NULL,
  crypto_currency_id INTEGER NOT NULL,
  amount NUMERIC(22,0) NOT NULL,
  operation_type VARCHAR(50) NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES "user"(id),
  CONSTRAINT fk_cryptocurrency FOREIGN KEY(crypto_currency_id) REFERENCES cryptocurrency(id)
);

INSERT INTO "cryptocurrency" ("id", "name", "symbol") VALUES
(1,	'Bitcoin',	'BTC'),
(2,	'Ethereum',	'ETH'),
(3,	'Tether',	'USDT'),
(4,	'XRP',	'XRP'),
(5,	'Polkadot',	'DOT'),
(6,	'Cardano',	'ADA'),
(7,	'Chainlink',	'LINK'),
(8,	'Litecoin',	'LTC'),
(9,	'Binance Coin',	'BNB'),
(10,	'Bitcoin Cash',	'BCH'),
(11,	'Stellar',	'XLM'),
(12,	'Dogecoin',	'DOGE'),
(13,	'USD Coin',	'USDC'),
(14,	'Aave',	'AAVE'),
(15,	'Uniswap',	'UNI'),
(16,	'Wrapped Bitcoin',	'WBTC'),
(17,	'Bitcoin SV',	'BSV'),
(18,	'EOS',	'EOS'),
(19,	'Monero',	'XMR'),
(20,	'NEM',	'XEM'),
(21,	'TRON',	'TRX'),
(22,	'Synthetix',	'SNX'),
(23,	'Tezos',	'XTZ'),
(24,	'Maker',	'MKR'),
(25,	'Compound',	'COMP'),
(26,	'THETA',	'THETA'),
(27,	'SushiSwap',	'SUSHI'),
(28,	'Cosmos',	'ATOM'),
(29,	'UMA',	'UMA'),
(30,	'VeChain',	'VET'),
(31,	'Dai',	'DAI'),
(32,	'Solana',	'SOL'),
(33,	'Neo',	'NEO'),
(34,	'Huobi Token',	'HT'),
(35,	'Crypto.com Coin',	'CRO'),
(36,	'Binance USD',	'BUSD'),
(37,	'UNUS SED LEO',	'LEO'),
(38,	'Terra',	'LUNA'),
(39,	'Elrond',	'EGLD'),
(40,	'FTX Token',	'FTT'),
(41,	'IOTA',	'MIOTA'),
(42,	'Avalanche',	'AVAX'),
(43,	'Celsius',	'CEL'),
(44,	'Dash',	'DASH'),
(45,	'Filecoin',	'FIL'),
(46,	'The Graph',	'GRT'),
(47,	'Zcash',	'ZEC'),
(48,	'Kusama',	'KSM'),
(49,	'Revain',	'REV'),
(50,	'Decred',	'DCR'),
(51,	'yearn.finance',	'YFI'),
(52,	'Algorand',	'ALGO'),
(53,	'Ethereum Classic',	'ETC'),
(54,	'Ren',	'REN'),
(55,	'Zilliqa',	'ZIL'),
(56,	'SwissBorg',	'CHSB'),
(57,	'Waves',	'WAVES'),
(58,	'0x',	'ZRX'),
(59,	'Nexo',	'NEXO'),
(60,	'NEAR Protocol',	'NEAR'),
(61,	'Curve DAO Token',	'CRV'),
(62,	'Loopring',	'LRC'),
(63,	'OMG Network',	'OMG'),
(64,	'Hedera Hashgraph',	'HBAR'),
(65,	'THORChain',	'RUNE'),
(66,	'renBTC',	'RENBTC'),
(67,	'1inch',	'1INCH'),
(68,	'Voyager Token',	'VGX'),
(69,	'Celo',	'CELO'),
(70,	'Ontology',	'ONT'),
(71,	'HedgeTrade',	'HEDG'),
(72,	'Basic Attention Token',	'BAT'),
(73,	'HUSD',	'HUSD'),
(74,	'Nano',	'NANO'),
(75,	'ICON',	'ICX'),
(76,	'DigiByte',	'DGB'),
(77,	'Quant',	'QNT'),
(78,	'BitTorrent',	'BTT'),
(79,	'Alpha Finance Lab',	'ALPHA'),
(80,	'Siacoin',	'SC'),
(81,	'Horizen',	'ZEN'),
(82,	'Reserve Rights',	'RSR'),
(83,	'TrueUSD',	'TUSD'),
(84,	'OKB',	'OKB'),
(85,	'Ampleforth',	'AMPL'),
(86,	'Fantom',	'FTM'),
(87,	'Qtum',	'QTUM'),
(88,	'Stacks',	'STX'),
(89,	'Kyber Network',	'KNC'),
(90,	'Enjin Coin',	'ENJ'),
(91,	'Ocean Protocol',	'OCEAN'),
(92,	'PancakeSwap',	'CAKE'),
(93,	'FunFair',	'FUN'),
(94,	'Verge',	'XVG'),
(95,	'Bancor',	'BNT'),
(96,	'IOST',	'IOST'),
(97,	'Decentraland',	'MANA'),
(98,	'TerraUSD',	'UST'),
(99,	'Bitcoin BEP2',	'BTCB'),
(100,	'Paxos Standard',	'PAX');

INSERT INTO "user" ("id", "username", "password", "email") VALUES
(1,	'freeman.mohr',	'0l6lyyy8x',	'Romana.Pagac@gmail.com'),
(2,	'tobias.shields',	's26i95xz49e4ko',	'Lasandra.Ward@gmail.com'),
(3,	'houston.luettgen',	'lkf9ttsxcy',	'Virgilio.Miller@gmail.com'),
(4,	'gladis.trantow',	'fcq9s1rmg',	'Colby.Wiza@gmail.com'),
(5,	'anita.flatley',	'3y23lwum',	'Clinton.Douglas@gmail.com'),
(6,	'belva.nitzsche',	'xrqgmnocosaqm',	'Reynalda.Simonis@gmail.com'),
(7,	'modesto.tromp',	'bw8n3cf9',	'Cristobal.Kub@gmail.com'),
(8,	'delcie.beatty',	'gb3uyxo4pmk9',	'Renato.Gerlach@gmail.com'),
(9,	'harris.heller',	'szzrv2defr',	'Hayden.Goyette@gmail.com'),
(10,	'victor.block',	'1ywk3oqq',	'Logan.Toy@gmail.com'),
(11,	'bobbi.grady',	'8yas0ov2scd',	'Laurence.Rosenbaum@gmail.com'),
(12,	'rosanna.leffler',	'9bvm81mkg',	'Ellsworth.Robel@gmail.com'),
(13,	'claud.cole',	'pnysduri10r5',	'Versie.Morar@gmail.com'),
(14,	'wilbert.spencer',	'1tcw01j6m',	'Curt.Leannon@gmail.com'),
(15,	'jody.daniel',	'avb30s61lwkg',	'Brice.Bergnaum@gmail.com'),
(16,	'marg.wiza',	'uas1ap2r4xl5',	'Clair.Welch@gmail.com'),
(17,	'kaylene.witting',	'bkgxa04sr7ed',	'Soon.Cole@gmail.com'),
(18,	'merlene.weimann',	'fd4e1lekm9xiw2',	'Colton.Rogahn@gmail.com'),
(19,	'russel.quitzon',	'logsrv9xpp',	'Daina.Kuhlman@gmail.com'),
(20,	'demetrius.greenfelder',	'eczqsqh4budxle',	'Michaela.Corkery@gmail.com'),
(21,	'denny.bayer',	'arhcaqjd7',	'Cheryll.Borer@gmail.com'),
(22,	'gearldine.robel',	'tds399v7n',	'Lanora.Runte@gmail.com'),
(23,	'richard.leannon',	'2cfiw7zt2v',	'Josiah.O''Connell@gmail.com'),
(24,	'dorsey.satterfield',	'mfxzhp3231q3z2c',	'Marceline.Nitzsche@gmail.com'),
(25,	'elisabeth.halvorson',	'tdpk0jxbz2st',	'Effie.Harber@gmail.com'),
(26,	'fallon.turner',	'55d5z8cv',	'Miles.Konopelski@gmail.com'),
(27,	'clemente.krajcik',	'ysie202bxm9owu0',	'Oren.Nikolaus@gmail.com'),
(28,	'jean.mraz',	'fjqmql4s',	'Romelia.Zieme@gmail.com'),
(29,	'hai.klein',	'uil3l3bng',	'Adeline.Halvorson@gmail.com'),
(30,	'yvone.kuhlman',	'odwkq329wmpq',	'Christeen.Kirlin@gmail.com'),
(31,	'alex.haag',	'hueh2j2yn5',	'Donnell.Zboncak@gmail.com'),
(32,	'krista.hessel',	'f3dcof99hbc',	'Garnet.Gottlieb@gmail.com'),
(33,	'alethia.schneider',	'2ugs3t0rc',	'Darcey.Becker@gmail.com'),
(34,	'ferdinand.bauch',	'puy7x7kz3t',	'Crista.Moen@gmail.com'),
(35,	'trey.abernathy',	'jpom4f25x19',	'Ben.Cremin@gmail.com'),
(36,	'rickey.kilback',	'8sdw7o4cor9obkl',	'Shena.Morissette@gmail.com'),
(37,	'carlee.rippin',	'mvw1o9sfmhont2',	'Candy.Weimann@gmail.com'),
(38,	'eddy.leffler',	'cchggeszk6w0',	'Wilhemina.Marquardt@gmail.com'),
(39,	'tanisha.jacobson',	'd9tllti8m5jqo',	'Malorie.Rippin@gmail.com'),
(40,	'efren.schaden',	'im958e1y',	'Isiah.Hoppe@gmail.com'),
(41,	'clint.bogan',	'ut7smk82nfhld',	'Artie.Fritsch@gmail.com'),
(42,	'kim.herzog',	'eaj84aw85ui',	'Katharina.Mraz@gmail.com'),
(43,	'virgilio.ondricka',	'v3jnx770rmaskv',	'Tinisha.Deckow@gmail.com'),
(44,	'debroah.rath',	'di5zibt6eeono',	'Star.Kohler@gmail.com'),
(45,	'meg.barrows',	'u5nd2gzmwzn',	'Donald.Ondricka@gmail.com'),
(46,	'bree.terry',	'ycpaiu620qg08',	'Jacques.Bogisich@gmail.com'),
(47,	'lesli.kertzmann',	'q5scoutvf04m3g9',	'Antione.Waters@gmail.com'),
(48,	'harris.waters',	'vrf4hclmw',	'Rosendo.Jacobi@gmail.com'),
(49,	'magan.witting',	'wraf00bxagtm662',	'Andree.Mayer@gmail.com'),
(50,	'edison.mraz',	'ox2vmyeufxj8',	'Ngan.Walker@gmail.com'),
(51,	'joaquin.denesik',	'jfa3hs3qy',	'Meridith.Gleason@gmail.com'),
(52,	'jacki.littel',	'rn3ryupxisuavg',	'Leoma.Keeling@gmail.com'),
(53,	'grayce.armstrong',	'ibqalza3psvs',	'Genaro.Doyle@gmail.com'),
(54,	'carter.hills',	'4sq3ox409oal',	'Sabrina.Kling@gmail.com'),
(55,	'reggie.hirthe',	'2j0bxs1hvzvg1wm',	'Holley.Boyle@gmail.com'),
(56,	'bernard.stroman',	'5328isd173g0c95',	'Val.Abbott@gmail.com'),
(57,	'monique.mertz',	'tg7953mtq',	'Herbert.Wintheiser@gmail.com'),
(58,	'corey.cummerata',	'iebttzxj',	'Julene.Boyle@gmail.com'),
(59,	'lorinda.windler',	'yahvq9aq',	'Bernard.Rau@gmail.com'),
(60,	'alejandra.hilll',	'zb79kczroxm51c',	'Lula.Boyle@gmail.com'),
(61,	'jamika.west',	'jekhea3p1ha',	'Jarred.Kunze@gmail.com'),
(62,	'isidro.mraz',	'k46r9kenclep77',	'Jimmy.Abbott@gmail.com'),
(63,	'britt.rempel',	'p6qw6138',	'Stacia.Wyman@gmail.com'),
(64,	'jocelyn.grimes',	'x176pkj83j',	'Sherrie.Lesch@gmail.com'),
(65,	'stanton.raynor',	'0bwai8ak2jbb',	'Jung.Walsh@gmail.com'),
(66,	'howard.hoeger',	'91lzg21178rrns',	'Dara.Schimmel@gmail.com'),
(67,	'tressa.willms',	'ynlpv87o4u',	'Blanch.Gislason@gmail.com'),
(68,	'jenice.jacobson',	'7n7obytvq',	'Georgeanna.Ondricka@gmail.com'),
(69,	'noe.yundt',	'c6cogh07ao02',	'Salina.Heathcote@gmail.com'),
(70,	'clark.becker',	'7kl454rqn',	'Gregg.Sporer@gmail.com'),
(71,	'bridgett.hegmann',	'i4ejb7jiv',	'Maribel.Lesch@gmail.com'),
(72,	'marica.block',	'y70l8isaj',	'Dominque.Ankunding@gmail.com'),
(73,	'jerrell.hudson',	'intfxyg0tqtklnm',	'Rigoberto.Lesch@gmail.com'),
(74,	'kiara.koss',	'ra5y4419k',	'Marlin.Abbott@gmail.com'),
(75,	'verdell.keeling',	'5w235265r8g6ps',	'Jeromy.Heller@gmail.com'),
(76,	'modesto.heller',	'5xywex1ctuota9',	'Lexie.Lakin@gmail.com'),
(77,	'gina.larkin',	'9qzvugg7k',	'Rena.Lubowitz@gmail.com'),
(78,	'avelina.damore',	'wnjgydgaazwb0n',	'Lucretia.Boehm@gmail.com'),
(79,	'karena.buckridge',	'qipe23tvcs',	'Willis.Abshire@gmail.com'),
(80,	'celina.hermiston',	'adma7spn',	'Kendall.Dooley@gmail.com'),
(81,	'shirlene.dare',	'xdysxj7x',	'Babette.Kilback@gmail.com'),
(82,	'juan.hoppe',	'ygj3sidx',	'Javier.Kuphal@gmail.com'),
(83,	'phillip.weimann',	'7rktwi7xc',	'Lea.Wisozk@gmail.com'),
(84,	'teri.dach',	'd68vaom3f0ni3',	'Aron.White@gmail.com'),
(85,	'marcelo.sawayn',	'3hrkcf6ubidwk5',	'Thaddeus.Farrell@gmail.com'),
(86,	'lottie.kautzer',	'm1blbmt9h6wuo6',	'Margarete.Kuphal@gmail.com'),
(87,	'tamara.boehm',	'dsnpnc5z',	'Asley.Kertzmann@gmail.com'),
(88,	'genaro.batz',	'nsdb1drpk',	'Andre.Champlin@gmail.com'),
(89,	'lauren.gerlach',	'fm2izq9cajqq',	'Lonnie.Bogan@gmail.com'),
(90,	'valentine.walter',	'wap7lv3ih3izqcl',	'Lakia.Graham@gmail.com'),
(91,	'gregory.harvey',	'magvzjbtlkuuw',	'Wiley.Beahan@gmail.com'),
(92,	'adalberto.pfannerstill',	'mqcl56y86k139',	'Roberta.Price@gmail.com'),
(93,	'ross.mohr',	'gmhisy9v7jj5',	'Jeanmarie.Grimes@gmail.com'),
(94,	'abby.mcclure',	'gvi8t20q7e',	'Annalee.McLaughlin@gmail.com'),
(95,	'jonna.oconner',	'8tao7j9h9i30ng',	'Alison.Sanford@gmail.com'),
(96,	'dannie.larson',	'rap6k0sbwjl',	'Sydney.Schumm@gmail.com'),
(97,	'muriel.russel',	'qkjkqhjl8',	'Cyril.Sawayn@gmail.com'),
(98,	'harlan.larson',	'mlt6jmns0',	'Winona.Brown@gmail.com'),
(99,	'analisa.franecki',	'0snjt0kjg0r5k',	'Latrina.Carter@gmail.com'),
(100,	'eric.dietrich',	'mkrwc894nn9ir2',	'Hershel.Adams@gmail.com');